import 'package:chatbot_agents/models/ai_bot/ai_bot.dart';
import 'package:chatbot_agents/models/knowledge/knowledge.dart';
import 'package:chatbot_agents/models/knowledge/knowledge_unit.dart';

class FakeData {
  static List<AiBot> aiBots = [
    AiBot(
      createdAt: DateTime(2022, 1, 30),
      assistantName: 'Gemini',
      openAiAssistantId: '1',
      id: '1',
    ),
    AiBot(
      createdAt: DateTime(2023, 1, 30),
      assistantName: 'Bard',
      openAiAssistantId: '2',
      id: '2',
    ),
    AiBot(
      createdAt: DateTime(2024, 1, 30),
      assistantName: 'ChatGPT',
      openAiAssistantId: '3',
      id: '3',
    ),
    AiBot(
      createdAt: DateTime(2021, 1, 30),
      assistantName: 'Jarvis',
      openAiAssistantId: '4',
      id: '4',
    ),
  ];
  // static List<Prompt> prompts = [
  //   Prompt(
  //     id: '1',
  //     createdAt: DateTime(2022, 1, 30).toString(),
  //     updatedAt: DateTime(2022, 1, 30).toString(),
  //     userId: '1',
  //     title: 'Business Prompt 1',
  //     content: 'Business Content 1',
  //     description: 'Business Description 1',
  //     category: PromptCategory.business,
  //     isPublic: false,
  //     language: 'en',
  //     userName: 'John Doe',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '2',
  //     createdAt: DateTime(2023, 1, 30).toString(),
  //     updatedAt: DateTime(2023, 1, 30).toString(),
  //     userId: '1',
  //     title: 'Business Prompt 2',
  //     content: 'Business Content 2',
  //     description: 'Business Description 2',
  //     category: PromptCategory.business,
  //     isPublic: false,
  //     language: 'en',
  //     userName: 'John Doe',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '3',
  //     createdAt: DateTime(2022, 2, 1).toString(),
  //     updatedAt: DateTime(2022, 2, 1).toString(),
  //     userId: '2',
  //     title: 'Career Prompt 1',
  //     content: 'Career Content 1',
  //     description: 'Career Description 1',
  //     category: PromptCategory.career,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Jane Smith',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '4',
  //     createdAt: DateTime(2023, 2, 1).toString(),
  //     updatedAt: DateTime(2023, 2, 1).toString(),
  //     userId: '2',
  //     title: 'Career Prompt 2',
  //     content: 'Career Content 2',
  //     description: 'Career Description 2',
  //     category: PromptCategory.career,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Jane Smith',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '5',
  //     createdAt: DateTime(2022, 3, 1).toString(),
  //     updatedAt: DateTime(2022, 3, 1).toString(),
  //     userId: '3',
  //     title: 'Chatbot Prompt 1',
  //     content: 'Chatbot Content 1',
  //     description: 'Chatbot Description 1',
  //     category: PromptCategory.chatbot,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Alice Johnson',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '6',
  //     createdAt: DateTime(2023, 3, 1).toString(),
  //     updatedAt: DateTime(2023, 3, 1).toString(),
  //     userId: '3',
  //     title: 'Chatbot Prompt 2',
  //     content: 'Chatbot Content 2',
  //     description: 'Chatbot Description 2',
  //     category: PromptCategory.chatbot,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Alice Johnson',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '7',
  //     createdAt: DateTime(2022, 4, 1).toString(),
  //     updatedAt: DateTime(2022, 4, 1).toString(),
  //     userId: '4',
  //     title: 'Coding Prompt 1',
  //     content: 'Coding Content 1',
  //     description: 'Coding Description 1',
  //     category: PromptCategory.coding,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Bob Brown',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '8',
  //     createdAt: DateTime(2023, 4, 1).toString(),
  //     updatedAt: DateTime(2023, 4, 1).toString(),
  //     userId: '4',
  //     title: 'Coding Prompt 2',
  //     content: 'Coding Content 2',
  //     description: 'Coding Description 2',
  //     category: PromptCategory.coding,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Bob Brown',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '9',
  //     createdAt: DateTime(2022, 5, 1).toString(),
  //     updatedAt: DateTime(2022, 5, 1).toString(),
  //     userId: '5',
  //     title: 'Education Prompt 1',
  //     content: 'Education Content 1',
  //     description: 'Education Description 1',
  //     category: PromptCategory.education,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Charlie Davis',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '10',
  //     createdAt: DateTime(2023, 5, 1).toString(),
  //     updatedAt: DateTime(2023, 5, 1).toString(),
  //     userId: '5',
  //     title: 'Education Prompt 2',
  //     content: 'Education Content 2',
  //     description: 'Education Description 2',
  //     category: PromptCategory.education,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Charlie Davis',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '11',
  //     createdAt: DateTime(2022, 6, 1).toString(),
  //     updatedAt: DateTime(2022, 6, 1).toString(),
  //     userId: '6',
  //     title: 'Fun Prompt 1',
  //     content: 'Fun Content 1',
  //     description: 'Fun Description 1',
  //     category: PromptCategory.fun,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'David Evans',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '12',
  //     createdAt: DateTime(2023, 6, 1).toString(),
  //     updatedAt: DateTime(2023, 6, 1).toString(),
  //     userId: '6',
  //     title: 'Fun Prompt 2',
  //     content: 'Fun Content 2',
  //     description: 'Fun Description 2',
  //     category: PromptCategory.fun,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'David Evans',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '13',
  //     createdAt: DateTime(2022, 7, 1).toString(),
  //     updatedAt: DateTime(2022, 7, 1).toString(),
  //     userId: '7',
  //     title: 'Marketing Prompt 1',
  //     content: 'Marketing Content 1',
  //     description: 'Marketing Description 1',
  //     category: PromptCategory.marketing,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Eve Foster',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '14',
  //     createdAt: DateTime(2023, 7, 1).toString(),
  //     updatedAt: DateTime(2023, 7, 1).toString(),
  //     userId: '7',
  //     title: 'Marketing Prompt 2',
  //     content: 'Marketing Content 2',
  //     description: 'Marketing Description 2',
  //     category: PromptCategory.marketing,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Eve Foster',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '15',
  //     createdAt: DateTime(2022, 8, 1).toString(),
  //     updatedAt: DateTime(2022, 8, 1).toString(),
  //     userId: '8',
  //     title: 'Productivity Prompt 1',
  //     content: 'Productivity Content 1',
  //     description: 'Productivity Description 1',
  //     category: PromptCategory.productivity,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Frank Green',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '16',
  //     createdAt: DateTime(2023, 8, 1).toString(),
  //     updatedAt: DateTime(2023, 8, 1).toString(),
  //     userId: '8',
  //     title: 'Productivity Prompt 2',
  //     content: 'Productivity Content 2',
  //     description: 'Productivity Description 2',
  //     category: PromptCategory.productivity,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Frank Green',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '17',
  //     createdAt: DateTime(2022, 9, 1).toString(),
  //     updatedAt: DateTime(2022, 9, 1).toString(),
  //     userId: '9',
  //     title: 'SEO Prompt 1',
  //     content: 'SEO Content 1',
  //     description: 'SEO Description 1',
  //     category: PromptCategory.seo,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Grace Harris',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '18',
  //     createdAt: DateTime(2023, 9, 1).toString(),
  //     updatedAt: DateTime(2023, 9, 1).toString(),
  //     userId: '9',
  //     title: 'SEO Prompt 2',
  //     content: 'SEO Content 2',
  //     description: 'SEO Description 2',
  //     category: PromptCategory.seo,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Grace Harris',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '19',
  //     createdAt: DateTime(2022, 10, 1).toString(),
  //     updatedAt: DateTime(2022, 10, 1).toString(),
  //     userId: '10',
  //     title: 'Writing Prompt 1',
  //     content: 'Writing Content 1',
  //     description: 'Writing Description 1',
  //     category: PromptCategory.writing,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Hank Irving',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '20',
  //     createdAt: DateTime(2023, 10, 1).toString(),
  //     updatedAt: DateTime(2023, 10, 1).toString(),
  //     userId: '10',
  //     title: 'Writing Prompt 2',
  //     content: 'Writing Content 2',
  //     description: 'Writing Description 2',
  //     category: PromptCategory.writing,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Hank Irving',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '21',
  //     createdAt: DateTime(2022, 11, 1).toString(),
  //     updatedAt: DateTime(2022, 11, 1).toString(),
  //     userId: '11',
  //     title: 'Other Prompt 1',
  //     content: 'Other Content 1',
  //     description: 'Other Description 1',
  //     category: PromptCategory.other,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Ivy Johnson',
  //     isFavorite: false,
  //   ),
  //   Prompt(
  //     id: '22',
  //     createdAt: DateTime(2023, 11, 1).toString(),
  //     updatedAt: DateTime(2023, 11, 1).toString(),
  //     userId: '11',
  //     title: 'Other Prompt 2',
  //     content: 'Other Content 2',
  //     description: 'Other Description 2',
  //     category: PromptCategory.other,
  //     isPublic: true,
  //     language: 'en',
  //     userName: 'Ivy Johnson',
  //     isFavorite: false,
  //   ),
  // ];
  static List<Knowledge> knowledge = [
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Jarvis knowledge',
      description:
          'Despecto sufficio taceo spiritus est utpote verbum basium traho ager. Commemoro aro dolor utpote. Virtus voluptas spiritus benigne suadeo sed maiores amet. Attero urbs cubitum vacuus civitas patior ventosus. Decens cerno deripio cui verumtamen tui vulgaris volubilis aliquid. Deludo totam corrupti decimus cras balbus. Comedo amiculum damnatio sufficio aro defendo eum. Titulus vir deorsum autus.',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 2',
      description: 'Description 2',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 3',
      description: 'Description 3',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 4',
      description: 'Description 4',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 5',
      description: 'Description 5',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 6',
      description: 'Description 6',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 7',
      description: 'Description 7',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 8',
      description: 'Description 8',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 9',
      description: 'Description 9',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 10',
      description: 'Description 10',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 11',
      description: 'Description 11',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 12',
      description: 'Description 12',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 13',
      description: 'Description 13',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 14',
      description: 'Description 14',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 15',
      description: 'Description 15',
    ),
    Knowledge(
      id: "uniqueId",
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeName: 'Knowledge 16',
      description: 'Description 16',
    ),
  ];
  static List<KnowledgeUnit> knowledgeUnits = [
    KnowledgeUnit(
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 1',
      id: '1',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 2',
      id: '2',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 3',
      id: '3',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 4',
      id: '4',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 5',
      id: '5',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 6',
      id: '6',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 7',
      id: '7',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 8',
      id: '8',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2022, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 9',
      id: '9',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2023, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 10',
      id: '10',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2024, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit 11',
      id: '11',
    ),
    KnowledgeUnit(
      createdAt: DateTime(2021, 1, 30).toString(),
      userId: '1',
      knowledgeId: '1',
      name: 'Knowledge Unit',
      id: '12',
    ),
  ];
}
