on:
  pull_request:
    branches:
      - deploy
  push:
    branches:
      - deploy

name: "Build & Release android app bundle"
jobs:
  build:
    name: Build & Release android app bundle
    runs-on: windows-latest
    steps:
      # - run: |
      #     cat > assets/.env <<EOF
      #     FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}
      #     FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}
      #     FIREBASE_ANDROID_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_ANDROID_MESSAGING_SENDER_ID }}
      #     FIREBASE_ANDROID_PROJECT_ID=${{ secrets.FIREBASE_ANDROID_PROJECT_ID }}
      #     FIREBASE_ANDROID_STORAGE_BUCKET=${{ secrets.FIREBASE_ANDROID_STORAGE_BUCKET }}
      #     GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      #     JARVIS_URL=${{ secrets.JARVIS_URL }}
      #     KNOWLEDGE_URL=${{ secrets.KNOWLEDGE_URL }}
      #     EOF

      # 1. Kiểm tra mã nguồn từ repository
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}" >> assets/.env
          echo "FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}" >> assets/.env
          echo "FIREBASE_ANDROID_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_ANDROID_MESSAGING_SENDER_ID }}" >> assets/.env
          echo "FIREBASE_ANDROID_PROJECT_ID=${{ secrets.FIREBASE_ANDROID_PROJECT_ID }}" >> assets/.env
          echo "FIREBASE_ANDROID_STORAGE_BUCKET=${{ secrets.FIREBASE_ANDROID_STORAGE_BUCKET }}" >> assets/.env
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> assets/.env
          echo "JARVIS_URL=${{ secrets.JARVIS_URL }}" >> assets/.env
          echo "KNOWLEDGE_URL=${{ secrets.KNOWLEDGE_URL }}" >> assets/.env

          echo "FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}" >> ./.env
          echo "FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}" >> ./.env
          echo "FIREBASE_ANDROID_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_ANDROID_MESSAGING_SENDER_ID }}" >> ./.env
          echo "FIREBASE_ANDROID_PROJECT_ID=${{ secrets.FIREBASE_ANDROID_PROJECT_ID }}" >> ./.env
          echo "FIREBASE_ANDROID_STORAGE_BUCKET=${{ secrets.FIREBASE_ANDROID_STORAGE_BUCKET }}" >> ./.env
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> ./.env
          echo "JARVIS_URL=${{ secrets.JARVIS_URL }}" >> ./.env
          echo "KNOWLEDGE_URL=${{ secrets.KNOWLEDGE_URL }}" >> ./.env

      # 2. Cài đặt Java (cho build Android)
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
       
      # 3. Thiết lập Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # 4. Cấu hình Flutter và kiểm tra môi trường
      - run: flutter config --no-analytics
      - run: flutter doctor

      # 5. Cài dependencies
      - run: flutter pub get

      # # 6. Chạy kiểm thử tự động
      # - run: flutter test

      # 7. Build APK debug và AAB
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build appbundle --release

      # 8. Push APK Debug lên GitHub Releases
      - name: Push to Debug Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN_CICD }}
      
      # 9. Push APK Release và AAB lên GitHub Releases
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN_CICD }}
        
       # 10. Deploy APK lên Firebase App Distribution
      - name: Deploy APK to Firebase
        run: firebase appdistribution:distribute build/app/outputs/apk/debug/app-debug.apk \
             --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} #1:667330785565:android:29b374aac9c0ea8dfcf1f4  # App ID của Firebase
             
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Push to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/bundle/release/*.aab"
      #     tag: v1.0.${{github.run_number}}
      #     token: ${{secrets.TOKEN_CICD}}
